// Generated by scripts/gen_model_header.py — do not edit by hand.
//
// Source: data/artifacts/edge/speed_model_meta.json
// Model:  speed_model.tflite (34856 bytes, TF 2.21.0)
//
// Held-out accuracy of the model these constants belong to:
//   float MAE 4.024 m/s | int8 MAE 5.270 m/s
//   RMSE 5.259 m/s | R^2 0.424
//   baseline (predict train mean) MAE 6.093 m/s
//
// Regenerate after every retrain. A stale header biases every prediction by a
// constant offset that nothing in the build will flag.

#pragma once

#include <array>
#include <cstddef>

namespace drishti {

inline constexpr std::size_t kParamWindow   = 50;
inline constexpr std::size_t kParamFeatures = 6;
inline constexpr int         kParamRateHz   = 10;

// Channel order: ax, ay, az, gyro_yaw, gyro_pitch, gyro_roll
inline constexpr std::array<float, kParamFeatures> kFeatureMean = {
    -0.00529755652f, -0.0504267476f, 9.44077301f, -7.98559849e-05f, -0.00521366857f, 0.000423768652f
};
inline constexpr std::array<float, kParamFeatures> kFeatureStd = {
    1.69109249f, 1.55743361f, 0.853458107f, 0.112498984f, 0.229860529f, 0.137033924f
};

// Variance, i.e. kFeatureStd squared. Emitted rather than computed at the call
// site so nothing downstream can accidentally use std where variance is meant
// -- for gyro yaw the two differ by a factor of ~9, which would silently
// mis-scale the EKF's process noise rather than fail.
inline constexpr std::array<float, kParamFeatures> kFeatureVariance = {
    2.85979381f, 2.42559943f, 0.72839074f, 0.0126560213f, 0.0528358629f, 0.0187782965f
};

// The rate the MODEL was trained at. The handset polls its IMU far faster
// during a blackout (CLAUDE.md section 2 says 100 Hz), so samples must be
// decimated to this rate before they reach the window -- otherwise a 50-step
// window covers 0.5 s instead of 5 s and the model sees a distribution it was
// never trained on. ImuDecimator in DeadReckoning.h does that.
inline constexpr int kModelRateHz = 10;

// Measurement variance for the speed the model produces, in (m/s)^2.
//
// Taken from the model's own held-out RMSE (5.259 m/s), not
// guessed: R = RMSE^2 = 27.66. This is the approved
// treatment of the speed output as a WEAK SECONDARY measurement (REVISION.md
// Q3) -- large R makes the EKF lean on its process model and on map-matching
// rather than trusting a speed that is 4 m/s out on average.
inline constexpr float kSpeedMeasurementVariance = 27.656638f;

}  // namespace drishti
