// Generated by scripts/gen_model_header.py — do not edit by hand.
//
// Source: data/artifacts/edge/speed_model_meta.json
// Model:  speed_model.tflite (34856 bytes, TF 2.21.0)
//
// Held-out accuracy of the model these constants belong to:
//   float MAE 4.024 m/s | int8 MAE 5.270 m/s
//   RMSE 5.259 m/s | R^2 0.424
//   baseline (predict train mean) MAE 6.093 m/s
//
// Regenerate after every retrain. A stale header biases every prediction by a
// constant offset that nothing in the build will flag.

#pragma once

#include <array>
#include <cstddef>

namespace drishti {

inline constexpr std::size_t kParamWindow   = 50;
inline constexpr std::size_t kParamFeatures = 6;
inline constexpr int         kParamRateHz   = 10;

// Channel order: ax, ay, az, gyro_yaw, gyro_pitch, gyro_roll
inline constexpr std::array<float, kParamFeatures> kFeatureMean = {
    -0.00529755652f, -0.0504267476f, 9.44077301f, -7.98559849e-05f, -0.00521366857f, 0.000423768652f
};
inline constexpr std::array<float, kParamFeatures> kFeatureStd = {
    1.69109249f, 1.55743361f, 0.853458107f, 0.112498984f, 0.229860529f, 0.137033924f
};

}  // namespace drishti
