// Generated by scripts/gen_model_header.py -- do not edit by hand.
//
// Retained so older translation units keep compiling. The constants
// live in IMU_Constants.h; this is an alias, not a copy.
#pragma once

#include "IMU_Constants.h"
