#!/usr/bin/env python3
"""Emit IMU_Constants.h from speed_model_meta.json.

The C++ bridge needs the per-channel normalisation constants the model was
trained with. Hand-copying them is the obvious failure: a retrain shifts the
means, nobody updates the header, and every prediction is biased by a constant
the compiler cannot catch. This regenerates them, and stamps the metrics the
constants belong to so a stale header is visible on sight.

    python scripts/gen_model_header.py

Run it after every training run; the generated header is committed so an app
build does not depend on the artifacts directory being populated.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
META = ROOT / "data" / "artifacts" / "edge" / "speed_model_meta.json"
# Named IMU_Constants.h because that is what the C++ engine includes. It also
# still writes the older SpeedModelParams.h name so an existing translation
# unit including it keeps building; both are generated from the same meta and
# can never disagree.
HEADER = ROOT / "mobile-app" / "native" / "IMU_Constants.h"
LEGACY_HEADER = ROOT / "mobile-app" / "native" / "SpeedModelParams.h"


def main() -> int:
    if not META.exists():
        sys.exit(f"{META.relative_to(ROOT)} not found — run scripts/train_idr_speed.py first")

    meta = json.loads(META.read_text())
    mean = meta["normalization"]["mean"]
    std = meta["normalization"]["std"]
    names = meta["feature_order"]
    m = meta["metrics"]

    if not (len(mean) == len(std) == len(names)):
        sys.exit("meta.json is inconsistent: mean/std/feature_order differ in length")

    def row(values: list[float]) -> str:
        return ", ".join(f"{v:.9g}f" for v in values)

    body = f"""// Generated by scripts/gen_model_header.py — do not edit by hand.
//
// Source: data/artifacts/edge/speed_model_meta.json
// Model:  {meta['int8_model']} ({meta['int8_bytes']} bytes, TF {meta['tensorflow']})
//
// Held-out accuracy of the model these constants belong to:
//   float MAE {m['test_mae_ms']:.3f} m/s | int8 MAE {m['int8_mae_ms']:.3f} m/s
//   RMSE {m['test_rmse_ms']:.3f} m/s | R^2 {m['test_r2']:.3f}
//   baseline (predict train mean) MAE {m['baseline_mae_ms']:.3f} m/s
//
// Regenerate after every retrain. A stale header biases every prediction by a
// constant offset that nothing in the build will flag.

#pragma once

#include <array>
#include <cstddef>

namespace drishti {{

inline constexpr std::size_t kParamWindow   = {meta['window']};
inline constexpr std::size_t kParamFeatures = {meta['n_features']};
inline constexpr int         kParamRateHz   = {meta['sample_rate_hz']};

// Channel order: {', '.join(names)}
inline constexpr std::array<float, kParamFeatures> kFeatureMean = {{
    {row(mean)}
}};
inline constexpr std::array<float, kParamFeatures> kFeatureStd = {{
    {row(std)}
}};

// Variance, i.e. kFeatureStd squared. Emitted rather than computed at the call
// site so nothing downstream can accidentally use std where variance is meant
// -- for gyro yaw the two differ by a factor of ~9, which would silently
// mis-scale the EKF's process noise rather than fail.
inline constexpr std::array<float, kParamFeatures> kFeatureVariance = {{
    {row([v * v for v in std])}
}};

// The rate the MODEL was trained at. The handset polls its IMU far faster
// during a blackout (CLAUDE.md section 2 says 100 Hz), so samples must be
// decimated to this rate before they reach the window -- otherwise a 50-step
// window covers 0.5 s instead of 5 s and the model sees a distribution it was
// never trained on. ImuDecimator in DeadReckoning.h does that.
inline constexpr int kModelRateHz = {meta['sample_rate_hz']};

// Measurement variance for the speed the model produces, in (m/s)^2.
//
// Taken from the model's own held-out RMSE ({m['test_rmse_ms']:.3f} m/s), not
// guessed: R = RMSE^2 = {m['test_rmse_ms'] ** 2:.2f}. This is the approved
// treatment of the speed output as a WEAK SECONDARY measurement (REVISION.md
// Q3) -- large R makes the EKF lean on its process model and on map-matching
// rather than trusting a speed that is 4 m/s out on average.
inline constexpr float kSpeedMeasurementVariance = {m['test_rmse_ms'] ** 2:.6f}f;

}}  // namespace drishti
"""
    HEADER.write_text(body)
    # The legacy name is a thin include of the new one rather than a second
    # copy of the constants: two generated files with the same numbers is one
    # file too many to keep in step.
    LEGACY_HEADER.write_text(
        "// Generated by scripts/gen_model_header.py -- do not edit by hand.\n"
        "//\n"
        "// Retained so older translation units keep compiling. The constants\n"
        "// live in IMU_Constants.h; this is an alias, not a copy.\n"
        "#pragma once\n\n"
        '#include "IMU_Constants.h"\n')
    print(f"wrote {HEADER.relative_to(ROOT)}")
    print(f"  window {meta['window']} x {meta['n_features']} @ {meta['sample_rate_hz']} Hz")
    print(f"  float MAE {m['test_mae_ms']:.3f} m/s, int8 MAE {m['int8_mae_ms']:.3f} m/s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
